services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: fhtw
      POSTGRES_DB: paperless
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d paperless"]
      interval: 5s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # messaging port
      - "15672:15672"  # management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ocrworker:
    build: ./PaperlessOCR
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: pass
      RABBITMQ_QUEUE: documents

  rest:
    build: ./PaperlessRest
    ports:
      - "5281:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=paperless;Username=test;Password=fhtw
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: user
      RabbitMQ__Pass: pass
      MinIO__Endpoint: minio:9000
      MinIO__AccessKey: paperless
      MinIO__SecretKey: paperlesssecret123
      MinIO__Bucket: documents
      MinIO__UseSSL: "false"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: paperless
      MINIO_ROOT_PASSWORD: paperlesssecret123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./PaperlessUI
    ports:
      - "80:80"
    depends_on:
      - rest

volumes:
  minio_data:
  postgres_data:
