services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-paperless}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-test} -d ${POSTGRES_DB:-paperless}"]
      interval: 5s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ocrworker:
    build:
        context: .
        dockerfile: PaperlessOCR/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_INPUTQUEUE: documents
      RABBITMQ_OCR_FINISHED_QUEUE: ocr_finished
      MINIO__ENDPOINT: minio:9000
      MINIO__ACCESSKEY: ${MINIO__ACCESSKEY}
      MINIO__SECRETKEY: ${MINIO__SECRETKEY}
      MINIO__USESSL: "false"

  aiworker:
    build: 
        context: .
        dockerfile: PaperlessAI/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_INPUTQUEUE: ocr_finished
      RABBITMQ_GENAI_FINISHED: genai_finished
      GEMINI_API_KEY: ${GEMINI_API_KEY}
        
  rest:
    build: 
        context: .
        dockerfile: PaperlessRest/Dockerfile
    ports:
      - "5281:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: ${RABBITMQ_USER:-user}
      RabbitMQ__Pass: ${RABBITMQ_PASS}
      MinIO__Endpoint: minio:9000
      MinIO__AccessKey: ${MINIO__ACCESSKEY}
      MinIO__SecretKey: ${MINIO__SECRETKEY}
      MinIO__Bucket: documents
      MinIO__UseSSL: "false"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-paperless}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./PaperlessUI
    ports:
      - "80:80"
    depends_on:
      - rest

volumes:
  minio_data:
  postgres_data:
